### ISSUE TITLE
Internal server error on full source download

### ISSUE THREAD

**Issue by nsmarkop** [qmk/qmk_configurator#869] opened 2021-01-10 00:35 UTC
When I try to click "full source", I get the following redirected to a page with the following text:

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Clicking "firmware" and getting the compiled hex/bin file works as expected, though. I've attached two keymaps, one for ergodox and one for planck, where this error happens (.json files renamed as .txt because GitHub apparently doesn't allow attaching .json files).

[ergodox_example.txt](https://github.com/qmk/qmk_configurator/files/5792033/ergodox_example.txt)
[planck_example.txt](https://github.com/qmk/qmk_configurator/files/5792034/planck_example.txt)

**Comment by zvecr** [comment] 2021-01-10 01:25
Duplicate of <https://github.com/qmk/qmk_api/issues/50>

**Closed by zvecr** 2021-01-10 01:25 UTC
Labels: duplicate
