### ISSUE TITLE
Volume up mapping is not working

### ISSUE THREAD

**Issue by link6155** [qmk/qmk_configurator#224] opened 2018-12-09 21:34 UTC
When I assign a key to be volume up in the configurator and then flash it onto my keyboard (Chimera Ortho), it doesn't do anything. The volume down and mute key works however and if I use the "Any" function to manually input the keycode, it works.

**Comment by yanfali** [comment] 2018-12-09 21:43
Thanks for reporting this. Looks like a keycode may have been mismapped. What code works for you in ANY?

**Comment by yanfali** [comment] 2018-12-09 21:43
@noroadsleft you want to check this out? I believe you were in there last. Thanks

**Comment by noroadsleft** [comment] 2018-12-09 22:03
Source looks okay from what I can tell so far. Let me build a keymap and flash it and see what happens. I'll reply again.

**Comment by noroadsleft** [comment] 2018-12-09 22:17
Tested and working as intended on my KC60.

@link6155 Do other keycodes (something other than volume control) work on the same switch, in that layer or others?

**Comment by yanfali** [comment] 2019-02-08 07:40
@link6155 any updates, or should we close this?

**Comment by yanfali** [comment] 2019-02-11 17:42
@link6155 feel free to re-open, but we're going to close this for now.

**Closed by yanfali** 2019-02-11 17:42 UTC
