### ISSUE TITLE
[Bug] Key Mapping Rearranged Unexpectedly After JSON Import on kinesis/kintlc

### ISSUE THREAD

**Issue by conceptual-perception** [qmk/qmk_configurator#1332] opened 2024-02-25 05:45 UTC
### Describe the Bug

I have a set of JSON files for a keyboard layout I've been modifying for the last two years. These JSON files have been used exclusively with QMK Configurator.

The keyboard is `kinesis/kintlc`. My JSON is [ariadne-4-jan-2023-v2.json](https://github.com/qmk/qmk_configurator/files/14395376/ariadne-4-jan-2023-v2.json)

**Expected Behavior**
* Layer 0 looks like Dvorak

* Layer 3 looks like QWERTY

**Observed Behavior**

I import `ariadne-4-jan-2023-v2` and notice the following on layer 0

* Function keys on the home row
* Numerical keys where the function keys should be

There is other stuff wrong, but that's a start. 

### Additional Context?

![image](https://github.com/qmk/qmk_configurator/assets/40440103/4fac30c1-7a2a-46e4-a84e-710896aef083)

**Comment by tzarc** [comment] 2024-02-25 10:57
I'd hazard a guess and say https://github.com/qmk/qmk_configurator/pull/1312 is the cause here.

**Comment by tzarc** [comment] 2024-02-25 10:59
Seems someone may have made some sort of conversion script on the kint side of things: https://github.com/kinx-project/kint/issues/76

**Comment by yanfali** [comment] 2024-11-08 09:01
ok, this seems resolved. so closing for now. thanks.

**Closed by yanfali** 2024-11-08 09:01 UTC
Labels: bug
