### ISSUE TITLE
[Bug] certificate expired

### ISSUE THREAD

**Issue by tompi** [qmk/qmk_configurator#1094] opened 2022-03-02 20:38 UTC
### Describe the Bug

Hi, not sure if this is the right place, but certificate expired, rendering online qmk configurator unusable:

<img width="1031" alt="Screenshot 2022-03-02 at 21 39 18" src="https://user-images.githubusercontent.com/231717/156445893-d97b8a35-d679-490d-ad2b-e0e85a497e3a.png">

<img width="598" alt="Screenshot 2022-03-02 at 21 37 04" src="https://user-images.githubusercontent.com/231717/156445673-fe358f07-f570-4ec2-906a-1039767e647b.png">

**Comment by zvecr** [comment] 2022-03-02 20:53
Duplicate of #1093

**Closed by zvecr** 2022-03-02 20:53 UTC
Labels: bug, duplicate
